site_name: SMC (Source Memory Chips) | Technical Documentation & Datasheets
theme:
  name: readthedocs
nav:
  - Home: index.md
  - eMMC Solutions:
    - SMC KLMBG2JETD Datasheet: emmc/klmbg2jetd.md
  - DDR Solutions:
    - SMC M324R4GA3BB0-CQK Datasheet: ddr/m324r4ga3bb0-cqk.md
  - LPDDR Solutions:
    - Coming Soon: lpddr/readme.md
